// libs
import type { Metadata } from "next";

// components
import Header from "../../components/Header";
import Sidebar from "../../components/Sidebar";
import Footer from "../../components/Footer";

// metadata
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="h-screen flex flex-col">
      <Header />
      <div className="flex h-full">
        <Sidebar />
        {children}
      </div>
      <Footer />
    </main>
  );
}
