import type { Metadata } from "next";
import Header from "../../components/Header";
import Sidebar from "../../components/Sidebar";
import Footer from "../../components/Footer";
import { ToastContainer } from "react-toastify";
export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen flex flex-col">
          <ToastContainer />
          <Header />
          <div className="flex h-full">
            <Sidebar />
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
